ALTER TABLE SalesCo.dbo.LINE
ADD Timestamp datetime;
Go

CREATE TRIGGER trICE5
ON SalesCo.dbo.LINE AFTER Insert, Update
AS
BEGIN
UPDATE LINE
  SET Timestamp = GETDATE()
  FROM Inserted i
  WHERE LINE.INV_NUMBER = i. INV_NUMBER and LINE.LINE_NUMBER = i. LINE_NUMBER
END
Go

INSERT INTO LINE (INV_NUMBER,LINE_NUMBER,P_CODE,LINE_UNITS,LINE_PRICE)
VALUES
(1001,3,'WR3/TT3',1,119.95),
(1002,2,'2238/QPD',2,38.95);

UPDATE LINE SET LINE_UNITS=5 WHERE INV_NUMBER=1001 and 	LINE_NUMBER=1;
Go

SELECT * from LINE;
Go
